### ISSUE TITLE
clever repl command throws an error on Win7 64

### ISSUE THREAD

**Issue by fan250** [CleverStack/cleverstack-cli#25]
D:\PROJECTS\friend-around\backend>clever repl
  Finding seeds to target...
    Found CleverStack Backend (node-seed)...
  ModuleLoader Loading modules... +0ms
Welcome to CleverStack  using seed version 1.0.5
Type .commands or .help for a list of commands
cleverstack::local>
fs.js:427
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
TypeError: path must be a string
    at Object.fs.openSync (fs.js:427:18)
    at addHistory (C:\npm\node_modules\cleverstack-cli\lib\repl.js:37:11)
    at Object.<anonymous> (C:\npm\node_modules\cleverstack-cli\lib\repl.js:141:1
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by pilsy** [comment]
This has been fixed in the latest releases
