### ISSUE TITLE
problem with serve task

### ISSUE THREAD

**Issue by kucherenko** [CleverStack/cleverstack-cli#51]
:~/workspace/tmp/my-app$ clever serve
Running "nodemon:web" (nodemon) task
[nodemon] v1.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`

module.js:340
    throw err;
          ^
Error: Cannot find module 'connect-timeout'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/apk/workspace/tmp/my-app/backend/index.js:6:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
Running "clean:server" (clean) task

**Comment by pilsy** [comment]
This looks like it doesn't have the node modules installed, try running `clever setup`, if that still errors, run `npm cache clean` and try `clever setup` again
