### ISSUE TITLE
clever install clever-users fails

### ISSUE THREAD

**Issue by g1205610** [CleverStack/cleverstack-cli#70]
$ node --version
v0.10.38
$ cd test001038/backend/modules/
$ clever install clever-users
Attempting to install clever-users...
✔      Found CleverStack Backend (node-seed) in /Users/xxx/test001038/backend...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-users...
  ├── Installing NPM modules for clever-users...
✔    Successfully installed clever-users...
  ├── Installing module peerDependencies...
  ├── Installing peer dependencies within /Users/xxx/test001038/backend/modules/clever-users
  ├── Installing modules: clever-auth@~1.2.x clever-accounts@~1.2.x
✔      Found CleverStack Backend (node-seed) in /Users/xxx/test001038/backend...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-accounts...
  ├── ⚠ Installing clever-auth...
  ├── Installing NPM modules for clever-accounts...
✔    Successfully installed clever-accounts...
  ├── Installing NPM modules for clever-auth...
✔    Successfully installed clever-auth...
  ├── Installing module peerDependencies...
  ├── Installing peer dependencies within /Users/xxx/test001038/backend/modules/clever-accounts
Unhandled rejection TypeError: Object Error: Cannot find module 'config' has no method 'match'
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:94:17
    at process._tickCallback (node.js:448:13)
From previous event:
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:93:13
From previous event:
    at exports.readTasks (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:83:10)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:239:5
From previous event:
    at Object.exports.runTasks (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:235:10)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:128:20
    at iterate (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:165:9)
    at peerDependenciesInstalled (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:123:19)
    at done (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:135:19)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:32:16
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:114:17
    at process._tickCallback (node.js:448:13)
From previous event:
    at installModulePeerDependencies (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:113:16)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:124:9)
    at EventEmitter.<anonymous> (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:107:15)
    at EventEmitter.emit (events.js:92:17)
    at finish (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:107:17)
    at check (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:103:37)
    at onstat (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:184:13)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:133:22
    at Object.oncomplete (fs.js:108:15)

**Comment by pilsy** [comment]
I believe i have fixed the issues in [Release 1.2.7](https://github.com/CleverStack/cleverstack-cli/releases/tag/1.2.7) - can you please run `npm install -g cleverstack-cli` and try again?  (if your running that on linux/mac then you may need to use sudo)

However this may not be the issue here, have you set your NODE_PATH? see [Magic Modules - Setting your Node Path](http://cleverstack.io/documentation/backend/#setting-your-node-path) for more information.

**Comment by g1205610** [comment]
Yes, NODE_PATH is set, I have those lines in my ~/.bash_profile:

export PATH=$PATH:~/node/bin:~/node/usr/local/bin
export N_PREFIX=~/node
export NODE_PATH=~/node/usr/local/lib/node_modules

I'm using https://github.com/tj/n to have multiple node versions available. I only installed n and 0.10.x because in my case "clever init" didn't work properly with 0.12.

The output has changed slightly, the line numbers are different:
```
$ clever -V
1.2.7

$ clever install clever-users
Attempting to install clever-users...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-users...
  ├── Installing NPM modules for clever-users...
✔    Successfully installed clever-users...
  ├── Installing module peerDependencies...
  ├── Installing peer dependencies within /Users/xxx/test010/backend/modules/clever-users
  ├── Installing modules: clever-auth@~1.2.x clever-accounts@~1.2.x clever-roles@~1.2.x
✔      Found CleverStack Backend (node-seed) in /Users/xxx/test010/backend...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-accounts...
  ├── ⚠ Installing clever-roles...
  ├── ⚠ Installing clever-auth...
  ├── Installing NPM modules for clever-accounts...
✔    Successfully installed clever-accounts...
  ├── Installing NPM modules for clever-roles...
✔    Successfully installed clever-roles...
  ├── Installing NPM modules for clever-auth...
✔    Successfully installed clever-auth...
  ├── Installing module peerDependencies...
  ├── Installing peer dependencies within /Users/xxx/test010/backend/modules/clever-accounts
Unhandled rejection TypeError: Object Error: Cannot find module 'config' has no method 'match'
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:94:17
    at process._tickCallback (node.js:448:13)
From previous event:
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:93:13
From previous event:
    at exports.readTasks (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:83:10)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:230:5
From previous event:
    at Object.exports.runTasks (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:226:10)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:128:20
    at iterate (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:165:9)
    at peerDependenciesInstalled (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:123:19)
    at done (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:135:19)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:32:16
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:114:17
    at process._tickCallback (node.js:448:13)
From previous event:
    at installModulePeerDependencies (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:113:16)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:124:9)
    at EventEmitter.<anonymous> (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:107:15)
    at EventEmitter.emit (events.js:92:17)
    at finish (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:107:17)
    at check (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:103:37)
    at onstat (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:184:13)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:133:22
    at Object.oncomplete (fs.js:108:15)
´´´

**Comment by pilsy** [comment]
Sorry about my late reply, if your still having issues take a look at http://cleverstack.io/documentation/backend/#setting-your-node-path

### On Mac/Linux:
`export NODE_PATH=./lib/:./modules/`

### On Windows:
`set NODE_PATH=./lib/;./modules/`
