### ISSUE TITLE
clever install clever-subscription fails

### ISSUE THREAD

**Issue by g1205610** [CleverStack/cleverstack-cli#72]
$ node --version
v0.10.38
$ cd test001038/backend/modules/
$ clever install clever-subscription
Attempting to install clever-subscription...
  ├── Searching for modules...
  ├──   Searching NPM...
  ├──   Searching Bower...
  ├── ⚠ Installing clever-subscription...
  ├── Installing NPM modules for clever-subscription...
✔    Successfully installed clever-subscription...
  ├── Installing module peerDependencies...
Unhandled rejection TypeError: Object TypeError: Cannot call method 'indexOf' of undefined has no method 'match'
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:94:17
    at process._tickCallback (node.js:448:13)
From previous event:
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:93:13
From previous event:
    at exports.readTasks (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:83:10)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:239:5
From previous event:
    at Object.exports.runTasks (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/util/grunt.js:235:10)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:128:20
    at iterate (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:149:13)
    at Object.async.eachSeries (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:165:9)
    at peerDependenciesInstalled (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:123:19)
    at done (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:135:19)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:32:16
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:114:17
    at process._tickCallback (node.js:448:13)
From previous event:
    at installModulePeerDependencies (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:113:16)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:125:13
    at Array.forEach (native)
    at _each (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:46:24)
    at Object.async.each (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/async/lib/async.js:124:9)
    at EventEmitter.<anonymous> (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/lib/install.js:107:15)
    at EventEmitter.emit (events.js:92:17)
    at finish (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:107:17)
    at check (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:103:37)
    at onstat (/Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:184:13)
    at /Users/xxx/node/usr/local/lib/node_modules/cleverstack-cli/node_modules/findit/index.js:133:22
    at Object.oncomplete (fs.js:108:15)

**Comment by pilsy** [comment]
This module is fairly new and still has some errors, if it is not resolved by [Release 1.2.7](https://github.com/CleverStack/cleverstack-cli/releases/tag/1.2.7) then i will have to take a look at it when i get some time next week and get back to you.
