### ISSUE TITLE
Command failed: setup-protractor while using `clever init` fails

### ISSUE THREAD

**Issue by kmalakoff** [CleverStack/cleverstack-cli#80]
Just trying out after installing the cli:

```
Error: Command failed: /bin/sh -c npm run-script setup-protractor
 Status @ 4.783m |   Installation Progress: [▒▒▒▒▒▒▒▒--]  79 %   ┊   Installing:npm ERR! Darwin 14.5.0Installing protractor (this might take awhile)...   ┊   Stnpm ERR! argv "node" "/{dir}.nvm/versions/node/v0.12.7/bin/npm" "run-script" "setup-protractor"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the angular-seed@1.2.0-rc-2 setup-protractor script 'grunt webdriver:update'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt webdriver:update
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /{dir}/frontend/npm-debug.log

Error: Command failed: /bin/sh -c npm run-script setup-protractor

npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/{dir}/.nvm/versions/node/v0.12.7/bin/npm" "run-script" "setup-protractor"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE
npm ERR! angular-seed@1.2.0-rc-2 setup-protractor: `grunt webdriver:update`
npm ERR! Exit status 3
npm ERR! 
npm ERR! Failed at the angular-seed@1.2.0-rc-2 setup-protractor script 'grunt webdriver:update'.
npm ERR! This is most likely a problem with the angular-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt webdriver:update
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /{dir}/frontend/npm-debug.log

    at ChildProcess.exithandler (child_process.js:751:12)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
From previous event:
    at /{dir}/.nvm/versions/node/v0.12.7/lib/node_modules/cleverstack-cli/bin/clever-init:356:18
    at processImmediate [as _immediateCallback] (timers.js:367:17)
From previous event:
    at /{dir}/.nvm/versions/node/v0.12.7/lib/node_modules/cleverstack-cli/bin/clever-init:353:10
    at /{dir}/.nvm/versions/node/v0.12.7/lib/node_modules/cleverstack-cli/node_modules/mkdirp/index.js:30:20
    at FSReqWrap.oncomplete (fs.js:95:15)
```

**Comment by iancampelo** [comment]
Same to me!

**Comment by pilsy** [comment]
hey @kmalakoff and @iancampelo - take a look at https://github.com/CleverStack/cleverstack-cli/issues/76#issuecomment-121777570 it should help resolve the issue your having with CleverStack... i need to improve the front-end docs to include more detailed information about the NODE_PATH - but for most cases the requirements of the backend (node-seed) are the same (in relation to how to set and what to set the NODE_PATH to).

Thanks, let me know if that get's rid of the error :+1: 
Richard.

**Comment by pilsy** [comment]
Oh and also before i forget, you can skip the installation of protractor on the `init` and `setup` commands by using the `-S` command line argument when running the command, for info about this (or other flags) use `clever init -h` and `clever setup -h`
